export const employeeData = [
  {
    id: 1,
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@company.com",
    department: "Engineering",
    position: "Senior Developer",
    salary: 95000,
    hireDate: "2021-03-15",
    age: 32,
    location: "New York",
    performanceRating: 4.2,
    projectsCompleted: 12,
    isActive: true,
    skills: ["JavaScript", "React", "Node.js"],
    manager: "Sarah Johnson"
  },
  {
    id: 2,
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@company.com",
    department: "Marketing",
    position: "Marketing Manager",
    salary: 78000,
    hireDate: "2020-07-22",
    age: 29,
    location: "Los Angeles",
    performanceRating: 4.5,
    projectsCompleted: 8,
    isActive: true,
    skills: ["Digital Marketing", "SEO", "Analytics"],
    manager: "Michael Brown"
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@company.com",
    department: "Marketing",
    position: "VP Marketing",
    salary: 125000,
    hireDate: "2019-01-10",
    age: 38,
    location: "Los Angeles",
    performanceRating: 4.7,
    projectsCompleted: 15,
    isActive: true,
    skills: ["Strategy", "Leadership", "Brand Management"],
    manager: null
  },
  {
    id: 4,
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@company.com",
    department: "Engineering",
    position: "Engineering Manager",
    salary: 115000,
    hireDate: "2018-11-05",
    age: 35,
    location: "New York",
    performanceRating: 4.6,
    projectsCompleted: 18,
    isActive: true,
    skills: ["Team Leadership", "Architecture", "Python"],
    manager: "David Wilson"
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Wilson",
    email: "david.wilson@company.com",
    department: "Engineering",
    position: "CTO",
    salary: 180000,
    hireDate: "2017-05-12",
    age: 42,
    location: "New York",
    performanceRating: 4.8,
    projectsCompleted: 25,
    isActive: true,
    skills: ["Technical Strategy", "Leadership", "Cloud Architecture"],
    manager: null
  },
  {
    id: 6,
    firstName: "Lisa",
    lastName: "Garcia",
    email: "lisa.garcia@company.com",
    department: "Sales",
    position: "Sales Representative",
    salary: 65000,
    hireDate: "2022-02-28",
    age: 26,
    location: "Chicago",
    performanceRating: 3.9,
    projectsCompleted: 6,
    isActive: true,
    skills: ["CRM", "Negotiation", "Customer Relations"],
    manager: "Robert Martinez"
  },
  {
    id: 7,
    firstName: "Robert",
    lastName: "Martinez",
    email: "robert.martinez@company.com",
    department: "Sales",
    position: "Sales Manager",
    salary: 92000,
    hireDate: "2020-09-14",
    age: 34,
    location: "Chicago",
    performanceRating: 4.3,
    projectsCompleted: 11,
    isActive: true,
    skills: ["Sales Strategy", "Team Management", "B2B Sales"],
    manager: "Jennifer Lee"
  },
  {
    id: 8,
    firstName: "Jennifer",
    lastName: "Lee",
    email: "jennifer.lee@company.com",
    department: "Sales",
    position: "VP Sales",
    salary: 135000,
    hireDate: "2019-06-18",
    age: 40,
    location: "Chicago",
    performanceRating: 4.6,
    projectsCompleted: 16,
    isActive: true,
    skills: ["Strategic Sales", "Leadership", "Market Analysis"],
    manager: null
  },
  {
    id: 9,
    firstName: "James",
    lastName: "Anderson",
    email: "james.anderson@company.com",
    department: "HR",
    position: "HR Specialist",
    salary: 58000,
    hireDate: "2021-08-30",
    age: 28,
    location: "Austin",
    performanceRating: 4.0,
    projectsCompleted: 7,
    isActive: true,
    skills: ["Recruitment", "Employee Relations", "HRIS"],
    manager: "Karen White"
  },
  {
    id: 10,
    firstName: "Karen",
    lastName: "White",
    email: "karen.white@company.com",
    department: "HR",
    position: "HR Manager",
    salary: 85000,
    hireDate: "2019-12-02",
    age: 36,
    location: "Austin",
    performanceRating: 4.4,
    projectsCompleted: 13,
    isActive: true,
    skills: ["HR Strategy", "Policy Development", "Leadership"],
    manager: null
  }
];
